#!/usr/bin/env bash
# Assemble the static frontend bundle for a Hugging Face Static Space (free).
#
#   scripts/build-hf-frontend.sh https://raglens.onrender.com
#
# Produces build/hf-space/ with index.html, app.js, styles.css, a config.js
# pointing at the given backend URL, and a README.md with the `sdk: static`
# front-matter the Space needs. Push that directory to the Space repo.

set -euo pipefail

BACKEND_URL="${1:-}"
if [ -z "$BACKEND_URL" ]; then
  echo "usage: $0 <backend-url>   e.g. $0 https://raglens.onrender.com" >&2
  exit 1
fi
BACKEND_URL="${BACKEND_URL%/}"   # strip trailing slash

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/build/hf-space"

rm -rf "$OUT"
mkdir -p "$OUT"
cp "$ROOT/static/index.html" "$ROOT/static/app.js" "$ROOT/static/styles.css" "$OUT/"

cat > "$OUT/config.js" <<EOF
// Generated by scripts/build-hf-frontend.sh — do not edit here.
window.RAGLENS_API_BASE = "$BACKEND_URL";
EOF

cat > "$OUT/README.md" <<'EOF'
---
title: RAGLens
emoji: 🔍
colorFrom: blue
colorTo: purple
sdk: static
pinned: false
---

RAGLens frontend. The backend runs elsewhere; see window.RAGLENS_API_BASE in config.js.
Source: https://github.com/Sridharmalladi/RAGLens
EOF

echo "built $OUT"
ls -la "$OUT"
echo
echo "next:"
echo "  git clone https://huggingface.co/spaces/<user>/<space> /tmp/space"
echo "  cp -r $OUT/. /tmp/space/ && cd /tmp/space && git add -A && git commit -m 'frontend' && git push"
